#! /usr/bin/env ruby

$: << File.expand_path("../../lib", __FILE__)

require "clamp"
require "faith_and_farming/book"
require "paint"
require "yaml"

Clamp do

  option ["-f", "--from"], "PAGE", "first page", :default => 72, &method(:Integer)
  option ["-t", "--to"], "PAGE", "last page", :default => 720, &method(:Integer)
  option ["-p", "--page"], "PAGE", "only page" do |arg|
    self.from = self.to = arg
  end

  def pages
    FaithAndFarming::Book.pages(from..to)
  end

  def elements
    pages.elements
  end

  subcommand ["blocks", "b"], "display blocks" do

    def execute
      pages.each do |page|
        puts "\nPAGE #{page.page_index}"
        page.blocks.each do |block|
          bounds = block.bounds
          puts "\nBLOCK {left #{bounds.left}, right #{bounds.right}, top #{bounds.top}, bottom #{bounds.bottom}}\n\n"
          puts block.text.gsub(/^/, "  ")
        end
      end
    end

  end

  subcommand ["elements", "e"], "display page elements" do

    def execute
      elements.each do |element|
        type_name = element.class.name.sub(/.*::/,"")
        data = {"type" => type_name}.merge(element.to_h)
        puts YAML.dump(data)
      end
    end

  end

  subcommand ["names", "n"], "display entry names" do

    option ["-p", "--show-pages"], :flag, "show pages"
    option ["-e", "--show-errors"], :flag, "show errors"
    option ["-l", "--max-level"], "N", "maximum level", &method(:Integer)

    INDENT = Paint["| ", :faint]
    DOT = Paint["•", :faint]
    MARRIED = Paint[" = ", :cyan]
    ERROR = Paint["!!!", :red]

    def execute
      elements.each do |e|
        case e
        when FaithAndFarming::Book::Elements::StartOfPage
          @page_index = e.page_index
          puts "\n--- page #{e.page_index} ---" if show_pages?
        when FaithAndFarming::Book::Elements::Entry
          next if max_level && e.level > max_level
          indent = INDENT * (e.level - 1)
          puts "#{indent}#{DOT} #{entry_heading(e)}"
          if @last_entry && e.level > @last_entry.level + 1
            show_error("too deep", indent: indent)
          end
          e.errors.each do |error|
            show_error(error, indent: indent)
          end
          @last_entry = e
        end
      end
    end

    private

    def entry_heading(entry)
      entry.people.map(&:name).join(MARRIED)
    end

    def show_error(message, indent:)
      return unless show_errors?
      puts indent + Paint["!!! #{message}", :red]
    end

  end

  subcommand ["families", "f"], "display families" do

    def execute
      db = pages.family_tree
      db.families.each do |family|
        puts YAML.dump(family_data(family))
      end
    end

    def family_data(family)
      {}.tap do |h|
        h["husband"] = family.husband.name
        h["wife"] = family.wife.name
        h["children"] = family.children.map(&:name) unless family.children.empty?
      end
    end

  end

  subcommand ["gedcom"], "generate GEDCOM" do

    def execute
      pages.family_tree.write_gedcom($stdout)
    end

  end

  def run(*)
    super
  rescue Errno::EPIPE
  end

end
