#! /usr/bin/env ruby

$: << File.expand_path("../../lib", __FILE__)

require "clamp"
require "faith_and_farming/page"

Clamp do

  subcommand "page", "page commands" do

    parameter "N", "page number", :attribute_name => :page_no

    def execute
      page.blocks.each do |block|
        puts "\n---"
        block.paragraphs.each do |p|
          puts "\n"
          puts "{indent #{p.indent}}"
          puts p.text
        end
      end
    end

    private

    def page
      FaithAndFarming::Page.load(page_no)
    end

  end

end